name: Download Artifact from JFrog

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install JFrog CLI
        run: |
          curl -fL https://install-cli.jfrog.io | sh
          #sudo mv jf /usr/local/bin/


      - name: Configure JFrog CLI with Access Token
        run: |
          jf config add my-artifactory-server \
            --url=${{ secrets.JFROG_URL }} \
            --user=${{ secrets.JFROG_USER }} \
            --access-token=${{ secrets.JFROG_ACCESS_TOKEN }} \
            --interactive=false

      - name: Download Artifact
        run: |
          jfrog rt dl "my_vir-alpine/2.png" "downloads/" --server-id=my-artifactory-server
